### ISSUE TITLE
Where is 2019-04-10-emacs-wsl.md?

### ISSUE THREAD

**Issue by novoid** [fwinkelbauer/wiki#1]
In May, I found `https://github.com/fwinkelbauer/wiki/blob/master/posts/2019-04-10-emacs-wsl.md` and added it to my link collection.

However, this URL seems to be broken now and I wonder if its content is accessible anywhere else. Can you help me?

**Comment by fwinkelbauer** [comment]
Hey Karl, sorry about that!

I have moved that file over to [my blog](https://florianwinkelbauer.com/posts/2019-04-10-emacs-wsl/). The source can be found [here](https://github.com/fwinkelbauer/website/blob/master/content/posts/2019-04-10-emacs-wsl.md).

Oh by the way: Thanks for sharing your Emacs configuration. I've stolen [your holiday calendar](https://github.com/fwinkelbauer/emacs#org) :).

**Comment by novoid** [comment]
Thanks for the updated URLs!

ad Emacs config: You're welcome. I got the snippet from somewhere else as well ;-)
